//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFinal_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FinalDBContext : DbContext
    {
        public FinalDBContext()
            : base("name=FinalDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Commande> Commandes { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
        public virtual DbSet<Pay> Pays { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Voyage> Voyages { get; set; }
    
        public virtual ObjectResult<ListePaysProc_Result> ListePaysProc(Nullable<long> idContinent)
        {
            var idContinentParameter = idContinent.HasValue ?
                new ObjectParameter("IdContinent", idContinent) :
                new ObjectParameter("IdContinent", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListePaysProc_Result>("ListePaysProc", idContinentParameter);
        }
    }
}
